services:
    alfredoramos.mermaid.listener:
        class: alfredoramos\mermaid\event\listener
        arguments:
            - '@auth'
            - '@config'
            - '@language'
        tags:
            - { name: event.listener }
