services:
    alfredoramos.mermaid.listener:
        class: alfredoramos\mermaid\event\listener
        tags:
            - { name: event.listener }

    alfredoramos.mermaid.controller:
        class: alfredoramos\mermaid\controller\mermaid
        arguments:
            - '@controller.helper'
            - '@language'
